# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7318db2920c3bf651e95cb99834ab608b09f799c41e0505c3f70fe59bc84117894f4aac8d1d71da70f50e7fcde044d1854f120b8dd08847cf612a033522eba03

test:
  secret_key_base: 63fa0a7163ca63d228f7a135d8f4b5bf69d997493b3c4bcefb7a552de47cd14d50f9eac4940e608f12067eab95797dbd0c43a55008ac4f313d638ddf9e1bf6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
